// Generate the comment_bank seed migration from the approved master workbook
// (ACFM_Comment_Bank_MASTER.xlsx). This is the Lead-approved, refined comment
// bank and supersedes the two earlier seed migrations
// (20260508000001_seed_comment_bank_sem1_sem2.sql and
//  20260509000001_seed_comment_bank_sem3_sem6.sql).
//
// The generated migration REPLACES the bank: it deletes existing comment_bank
// rows that aren't referenced by any saved grade (all of them on a pre-launch
// DB), then inserts the master rows, mapping subject_code -> subjects.id so it
// is robust to whatever ids the subjects table assigned.
//
// Run:  node scripts/build_master_seed.cjs
const fs = require("fs");
const path = require("path");
const XLSX = require("xlsx");

const root = path.resolve(__dirname, "..");
const SRC = path.join(root, "ACFM_Comment_Bank_MASTER.xlsx");
const OUT = path.join(
  root,
  "supabase",
  "migrations",
  "20260612000000_seed_comment_bank_master.sql",
);

// Sheet (tab) name -> subjects.code in the database.
const SHEET_TO_CODE = {
  Direction: "direction",
  Production: "production",
  Screenwriting: "screenwriting",
  Cinematography: "cinematography",
  "Sound Design": "sound_design",
  Editing: "editing",
  VFX: "vfx",
};

const SEM_TO_NUM = {
  "SEM I": 1,
  "SEM II": 2,
  "SEM III": 3,
  "SEM IV": 4,
  "SEM V": 5,
  "SEM VI": 6,
};

const VALID_GRADES = new Set(["A", "B", "C", "D"]);

// Collapse spreadsheet line-wrap newlines / runs of whitespace into single
// spaces so each comment is one clean paragraph, and trim the ends.
const clean = (s) => String(s).replace(/\s+/g, " ").trim();
const sqlEscape = (s) => s.replace(/'/g, "''");

const wb = XLSX.readFile(SRC);

const rows = [];
let skippedBlank = 0;
const anomalies = [];
// dist[code][sem][grade] = count, for the report + gap detection.
const dist = {};

for (const sheet of wb.SheetNames) {
  const code = SHEET_TO_CODE[sheet];
  if (!code) {
    anomalies.push(`Unknown sheet "${sheet}" — not mapped to a subject, skipped.`);
    continue;
  }
  const aoa = XLSX.utils.sheet_to_json(wb.Sheets[sheet], {
    header: 1,
    defval: "",
  });
  // Row 0 is the header (Semester, Grade, Comment).
  for (let i = 1; i < aoa.length; i++) {
    const r = aoa[i];
    const semRaw = clean(r[0]);
    const gradeRaw = clean(r[1]).toUpperCase();
    const body = clean(r[2]);

    if (!semRaw && !gradeRaw && !body) continue; // wholly empty row
    if (!body) {
      skippedBlank++;
      continue; // placeholder row with no comment text
    }

    const semester = SEM_TO_NUM[semRaw.toUpperCase()];
    if (!semester) {
      anomalies.push(`${sheet} row ${i + 1}: bad semester "${semRaw}", skipped.`);
      continue;
    }
    if (!VALID_GRADES.has(gradeRaw)) {
      anomalies.push(`${sheet} row ${i + 1}: bad grade "${gradeRaw}", skipped.`);
      continue;
    }

    rows.push({ semester, code, grade: gradeRaw, body });
    ((dist[code] ??= {})[semester] ??= {})[gradeRaw] =
      (dist[code][semester]?.[gradeRaw] || 0) + 1;
  }
}

// De-duplicate exact (semester, code, grade, body) repeats so the NOT EXISTS
// insert guard can't trip over identical rows within one statement.
const seen = new Set();
const unique = [];
let dupes = 0;
for (const r of rows) {
  const k = `${r.semester}|${r.code}|${r.grade}|${r.body}`;
  if (seen.has(k)) {
    dupes++;
    continue;
  }
  seen.add(k);
  unique.push(r);
}

// Stable order in the file: subject, then semester, then grade A-D.
const GRADE_ORDER = { A: 0, B: 1, C: 2, D: 3 };
const SUBJECT_ORDER = Object.values(SHEET_TO_CODE);
unique.sort(
  (a, b) =>
    SUBJECT_ORDER.indexOf(a.code) - SUBJECT_ORDER.indexOf(b.code) ||
    a.semester - b.semester ||
    GRADE_ORDER[a.grade] - GRADE_ORDER[b.grade],
);

const values = unique
  .map(
    (r) => `  (${r.semester}, '${r.code}', '${r.grade}', '${sqlEscape(r.body)}')`,
  )
  .join(",\n");

const sql = `-- Seed the comment bank from the Lead-approved master workbook.
-- Source: ACFM_Comment_Bank_MASTER.xlsx (one sheet per subject).
-- Generated by scripts/build_master_seed.cjs — DO NOT hand-edit; regenerate.
--
-- This REPLACES the two earlier seed banks
-- (20260508000001_seed_comment_bank_sem1_sem2.sql,
--  20260509000001_seed_comment_bank_sem3_sem6.sql) with the refined wording.
--
-- ${unique.length} comments across ${SUBJECT_ORDER.length} subjects, Sem I-VI, grades A-D.
--
-- Replace strategy: delete existing comments that no saved grade references
-- (every comment on a pre-launch DB), then insert the master set. Comments
-- still referenced by a student_grades row are left untouched so the FK
-- (student_grades.comment_id ON DELETE RESTRICT) can't block this migration.

DELETE FROM public.comment_bank cb
WHERE NOT EXISTS (
  SELECT 1 FROM public.student_grades sg WHERE sg.comment_id = cb.id
);

INSERT INTO public.comment_bank (semester, subject_id, grade, body)
SELECT v.semester, s.id, v.grade, v.body
FROM (VALUES
${values}
) AS v(semester, subject_code, grade, body)
JOIN public.subjects s ON s.code = v.subject_code
WHERE NOT EXISTS (
  SELECT 1 FROM public.comment_bank cb
  WHERE cb.semester = v.semester
    AND cb.subject_id = s.id
    AND cb.body = v.body
);
`;

fs.writeFileSync(OUT, sql, "utf8");

// ---- Report ------------------------------------------------------------
const ROMAN = { 1: "I", 2: "II", 3: "III", 4: "IV", 5: "V", 6: "VI" };
console.log("Wrote", path.relative(root, OUT));
console.log(
  `Rows: ${rows.length} parsed, ${unique.length} unique` +
    (dupes ? ` (${dupes} exact dup(s) collapsed)` : "") +
    `, ${skippedBlank} blank skipped.`,
);

console.log("\nPer-subject / semester / grade coverage (expect 8 per cell):");
const gaps = [];
for (const code of SUBJECT_ORDER) {
  const subj = dist[code] || {};
  const total = Object.values(subj)
    .flatMap((g) => Object.values(g))
    .reduce((a, b) => a + b, 0);
  console.log(`  ${code.padEnd(15)} total=${total}`);
  for (let sem = 1; sem <= 6; sem++) {
    const g = subj[sem];
    if (!g) continue;
    const parts = ["A", "B", "C", "D"].map((gr) => `${gr}:${g[gr] || 0}`);
    const thin = ["A", "B", "C", "D"].filter((gr) => (g[gr] || 0) < 8);
    const line = `      Sem ${ROMAN[sem].padEnd(3)} ${parts.join("  ")}`;
    console.log(thin.length ? `${line}   <-- thin: ${thin.join(",")}` : line);
    for (const gr of thin)
      gaps.push(`${code} Sem ${ROMAN[sem]} ${gr}: only ${g[gr] || 0}`);
  }
}

if (anomalies.length) {
  console.log("\nANOMALIES:");
  for (const a of anomalies) console.log("  - " + a);
}
if (gaps.length) {
  console.log(
    `\nCOVERAGE GAPS (cells with <8 comments — source workbook is short here):`,
  );
  for (const g of gaps) console.log("  - " + g);
}
