-- Seed the comment bank for BA Sem I and Sem II (Phase 1).
-- 384 rows: 6 subjects x 4 grades (A-D) x 8 phrasings x 2 semesters.
-- Source: ACFM_Final_Working_System.xlsx 'Comment Bank' sheet.
-- Idempotent: skips rows whose (semester, subject_id, body) already exists.

INSERT INTO public.comment_bank (semester, subject_id, grade, body)
SELECT v.semester, s.id, v.grade, v.body
FROM (VALUES
  (1, 'direction', 'A', 'Direction: Demonstrates strong analytical ability in interpreting films, with clear understanding of directorial intent, visual language, and narrative construction.'),
  (1, 'direction', 'A', 'Direction: Applies visual storytelling techniques such as composition, camera angles, and continuity with clarity and purpose.'),
  (1, 'direction', 'A', 'Direction: Effectively translates real-world observations into structured visual narratives with originality and insight.'),
  (1, 'direction', 'A', 'Direction: Demonstrates a strong understanding of continuity and visual planning, ensuring clarity in scene progression and cinematic connection.'),
  (1, 'direction', 'A', 'Direction: Maintains a detailed and reflective film diary, demonstrating critical thinking and evolving directorial perspective.'),
  (1, 'direction', 'A', 'Direction: Actively engages in collaborative exercises, contributing effectively to camera, edit, and sound integration.'),
  (1, 'direction', 'A', 'Direction: Demonstrates strong awareness of time and space in filmmaking, constructing scenes with logical progression.'),
  (1, 'direction', 'A', 'Direction: Shows initiative in exploring different filmmaking approaches through case studies and practical exercises.'),
  (1, 'direction', 'B', 'Direction: Shows a good understanding of film analysis, though insights tend to remain descriptive rather than deeply critical.'),
  (1, 'direction', 'B', 'Direction: Demonstrates working knowledge of visual storytelling techniques and can further improve consistency in execution.'),
  (1, 'direction', 'B', 'Direction: Engages with observational exercises, though translation into compelling visual narratives needs refinement.'),
  (1, 'direction', 'B', 'Direction: Understands the basics of continuity and decoupage and can further develop clarity in complex scenes.'),
  (1, 'direction', 'B', 'Direction: Maintains a film diary and can further improve consistency and depth in reflections.'),
  (1, 'direction', 'B', 'Direction: Participates in collaborative exercises and can contribute more proactively to collaborative processes.'),
  (1, 'direction', 'B', 'Direction: Shows awareness of time and space in scenes and can further improve precision in execution.'),
  (1, 'direction', 'B', 'Direction: Demonstrates familiarity with different filmmaking approaches, can develop strong personal interpretation.'),
  (1, 'direction', 'C', 'Direction: Can further improve engagement with film analysis by moving beyond surface-level observations.'),
  (1, 'direction', 'C', 'Direction: Can further develop the application of visual storytelling principles to achieve clearer visual communication.'),
  (1, 'direction', 'C', 'Direction: Observational exercises can be further developed with greater clarity and structure in visual narratives.'),
  (1, 'direction', 'C', 'Direction: Can further develop understanding of continuity to achieve greater consistency in scene construction.'),
  (1, 'direction', 'C', 'Direction: Film diary can be improved through more consistent reflection and critical engagement.'),
  (1, 'direction', 'C', 'Direction: Can maximize participation in collaborative exercises to strengthen overall output.'),
  (1, 'direction', 'C', 'Direction: Can further improve understanding of spatial and temporal relationships within scenes.'),
  (1, 'direction', 'C', 'Direction: Can further explore and apply different filmmaking approaches through practical exercises.'),
  (1, 'direction', 'D', 'Direction: Can engage more actively with film analysis to strengthen understanding of cinematic language.'),
  (1, 'direction', 'D', 'Direction: Can further develop the application of fundamental visual storytelling principles such as composition and continuity.'),
  (1, 'direction', 'D', 'Direction: Can engage more meaningfully with observational exercises to develop narrative interpretation skills.'),
  (1, 'direction', 'D', 'Direction: Can improve understanding of continuity and decoupage to achieve clearer and more coherent scene construction.'),
  (1, 'direction', 'D', 'Direction: Film diary can be further developed to meet academic requirements with greater reflection and consistency.'),
  (1, 'direction', 'D', 'Direction: Can participate more actively in collaborative exercises to strengthen learning and group contribution.'),
  (1, 'direction', 'D', 'Direction: Can further develop understanding of time and space in filmmaking through practical exercises.'),
  (1, 'direction', 'D', 'Direction: Can show greater initiative in engaging with course content and practical exercises.'),
  (1, 'screenwriting', 'A', 'Screenwriting: Demonstrates strong ability to develop original concepts, supported by clear research and well-defined narrative intent.'),
  (1, 'screenwriting', 'A', 'Screenwriting: Shows a clear understanding of story fundamentals, including premise, conflict, and character motivation, with effective application.'),
  (1, 'screenwriting', 'A', 'Screenwriting: Writes with clarity and visual awareness, translating ideas into scenes that are cinematic and engaging.'),
  (1, 'screenwriting', 'A', 'Screenwriting: Demonstrates strong control over basic story structure, creating coherent narratives using the three-act framework.'),
  (1, 'screenwriting', 'A', 'Screenwriting: Shows originality and depth in creative writing exercises, with a distinct narrative voice and perspective.'),
  (1, 'screenwriting', 'A', 'Screenwriting: Effectively develops characters with clear motivations that contribute to meaningful narrative progression.'),
  (1, 'screenwriting', 'A', 'Screenwriting: Demonstrates strong observational skills, translating real-life experiences into compelling story ideas.'),
  (1, 'screenwriting', 'A', 'Screenwriting: Actively engages with reading and analysis of stories, applying insights to their own writing practice'),
  (1, 'screenwriting', 'B', 'Screenwriting: Shows a good understanding of concept development, though ideas require further refinement and clarity.'),
  (1, 'screenwriting', 'B', 'Screenwriting: Demonstrates familiarity with story fundamentals, with scope to further strengthen consistency in handling conflict and character motivation.'),
  (1, 'screenwriting', 'B', 'Screenwriting: Writes with basic clarity, and can further enhance scenes by developing stronger visual and cinematic detail.'),
  (1, 'screenwriting', 'B', 'Screenwriting: Understands the three-act structure, though narrative progression can be developed further to feel more engaging and dynamic.'),
  (1, 'screenwriting', 'B', 'Screenwriting: Shows effort in creative writing, with scope to further strengthen originality and depth.'),
  (1, 'screenwriting', 'B', 'Screenwriting: Develops characters with some clarity, with scope to build stronger individuality and depth.'),
  (1, 'screenwriting', 'B', 'Screenwriting: Engages with observational exercises, though translation into strong story ideas needs development.'),
  (1, 'screenwriting', 'B', 'Screenwriting: Demonstrates engagement with reading tasks, though application of insights into writing is still developing.'),
  (1, 'screenwriting', 'C', 'Screenwriting: Shows developing clarity in concept development, though ideas still need stronger focus and refinement.'),
  (1, 'screenwriting', 'C', 'Screenwriting: Shows partial understanding of story fundamentals, with scope to strengthen clarity in conflict development.'),
  (1, 'screenwriting', 'C', 'Screenwriting: Writing shows developing visual clarity, with scope to better translate ideas into cinematic scenes.'),
  (1, 'screenwriting', 'C', 'Screenwriting: Shows developing understanding of story structure, though narratives may feel uneven or incomplete at times.'),
  (1, 'screenwriting', 'C', 'Screenwriting: Creative writing exercises show scope for further development in originality and depth, moving beyond predictable ideas.'),
  (1, 'screenwriting', 'C', 'Screenwriting: Characters show emerging development, though motivations and narrative contribution can be strengthened.'),
  (1, 'screenwriting', 'C', 'Screenwriting: Observational exercises show potential, though translation into usable story material needs further development.'),
  (1, 'screenwriting', 'C', 'Screenwriting: Shows developing engagement with reading and analysis tasks, with scope to further strengthen application in writing.'),
  (1, 'screenwriting', 'D', 'Screenwriting: Shows emerging understanding of concept development, though ideas require further clarity and completion.'),
  (1, 'screenwriting', 'D', 'Screenwriting: Shows emerging familiarity with basic story elements such as premise, conflict, and character, with scope for stronger understanding.'),
  (1, 'screenwriting', 'D', 'Screenwriting: Writing shows limited clarity and needs further development to achieve cinematic readability as a screenplay.'),
  (1, 'screenwriting', 'D', 'Screenwriting: Shows early-stage understanding of basic story structure, with scope for further development.'),
  (1, 'screenwriting', 'D', 'Screenwriting: Creative writing exercises show scope for greater completion and development of ideas.'),
  (1, 'screenwriting', 'D', 'Screenwriting: Characters show early-stage development and need further clarity in definition and purpose.'),
  (1, 'screenwriting', 'D', 'Screenwriting: Observational and ideation exercises show initial engagement, with scope for further development.'),
  (1, 'screenwriting', 'D', 'Screenwriting: Engagement with reading and analysis tasks is developing, with scope to strengthen participation and application.'),
  (1, 'cinematography', 'A', 'Demonstrates clear and confident control over exposure and colour, maintaining consistency across shots.'),
  (1, 'cinematography', 'A', 'Applies lenses and depth of field purposefully to enhance visual storytelling.'),
  (1, 'cinematography', 'A', 'Uses composition and camera angles thoughtfully to create engaging and well-structured frames.'),
  (1, 'cinematography', 'A', 'Maintains strong continuity, ensuring smooth visual flow across shots.'),
  (1, 'cinematography', 'A', 'Utilizes close-ups and framing effectively to communicate intent and guide viewer attention.'),
  (1, 'cinematography', 'A', 'Maintains consistent technical control over exposure and white balance throughout.'),
  (1, 'cinematography', 'A', 'Demonstrates a strong understanding of visual storytelling through deliberate and effective choices.'),
  (1, 'cinematography', 'A', 'Overall work reflects clarity of intent, technical control and strong visual awareness.'),
  (1, 'cinematography', 'B', 'Demonstrates a good understanding of exposure and colour, with scope to improve consistency across shots.'),
  (1, 'cinematography', 'B', 'Applies lenses and depth of field with awareness and can refine control to strengthen visual impact.'),
  (1, 'cinematography', 'B', 'Uses composition and camera angles effectively in parts, with greater consistency enhancing overall frame quality.'),
  (1, 'cinematography', 'B', 'Maintains basic continuity and can improve visual flow by refining shot transitions.'),
  (1, 'cinematography', 'B', 'Uses close-ups and framing with intent and can strengthen their impact through more purposeful application.'),
  (1, 'cinematography', 'B', 'Maintains generally sound technical control, with further refinement in exposure and white balance improving consistency.'),
  (1, 'cinematography', 'B', 'Shows a clear understanding of visual storytelling, with more deliberate choices can strengthen narrative clarity.'),
  (1, 'cinematography', 'B', 'Overall work is competent and well-structured, with clear potential to refine both technical control and visual decisions.'),
  (1, 'cinematography', 'C', 'Shows a basic understanding of exposure and colour and can improve by developing more consistent control across shots.'),
  (1, 'cinematography', 'C', 'Applies lenses and depth of field at a basic level and can strengthen their impact through more purposeful use.'),
  (1, 'cinematography', 'C', 'Composition and camera angles show initial application and can improve by making clearer framing decisions.'),
  (1, 'cinematography', 'C', 'Maintains continuity in parts and can strengthen overall flow by paying closer attention to shot connections.'),
  (1, 'cinematography', 'C', 'Uses close-ups and framing with some intent and can improve their effectiveness by aligning them more clearly with the narrative.'),
  (1, 'cinematography', 'C', 'Technical execution shows inconsistency and can improve through more careful control of exposure and white balance.'),
  (1, 'cinematography', 'C', 'Demonstrates a developing understanding of visual storytelling and can grow by making more deliberate visual choices.'),
  (1, 'cinematography', 'C', 'Overall work reflects a basic level of understanding and can be strengthened through consistent practice and refinement.'),
  (1, 'cinematography', 'D', 'Is at an early stage in understanding exposure and colour and should focus on building consistent control across shots.'),
  (1, 'cinematography', 'D', 'Is beginning to explore lenses and depth of field and can improve by learning how they shape the image.'),
  (1, 'cinematography', 'D', 'Composition and camera angles require further development and can improve by focusing on basic framing principles.'),
  (1, 'cinematography', 'D', 'Continuity across shots needs attention and can be developed by practicing simple shot connections and screen direction.'),
  (1, 'cinematography', 'D', 'Close-ups and framing need clearer intent and can improve by understanding their role in storytelling.'),
  (1, 'cinematography', 'D', 'Technical control of exposure and white balance requires development and can be strengthened through guided practice.'),
  (1, 'cinematography', 'D', 'Understanding of visual storytelling is at an early stage and can grow by focusing on how shots communicate meaning.'),
  (1, 'cinematography', 'D', 'Overall work indicates the need to build stronger foundational skills, which can be developed through consistent practice and guidance.'),
  (1, 'editing', 'A', 'Editing: Demonstrates strong control over continuity, progression, and emotional timing. Continue refining shot duration and emotional layering to develop greater precision in storytelling.'),
  (1, 'editing', 'A', 'Editing: Shows confident shot arrangement and clear viewer guidance. Further explore expressive pacing and reaction timing to deepen emotional impact.'),
  (1, 'editing', 'A', 'Editing: Uses pauses and rhythm effectively to shape scenes. Focus on improving continuity precision and transition smoothness for a more polished output.'),
  (1, 'editing', 'A', 'Editing: Strong technical execution and clear narrative progression are evident. Continue developing more nuanced emotional shaping through shot selection and timing.'),
  (1, 'editing', 'A', 'Editing: Demonstrates good understanding of expressive cutting beyond functional continuity. Refine pacing choices further to strengthen dramatic emphasis.'),
  (1, 'editing', 'A', 'Editing: Shot duration and progression are handled with maturity. Continue experimenting with emotional rhythm and viewer attention control.'),
  (1, 'editing', 'A', 'Editing: Frames, inserts, and shot sizes are used purposefully. Improve timing precision further to enhance narrative flow and engagement.'),
  (1, 'editing', 'A', 'Editing: Maintains a strong balance between storytelling, emotion, and technical execution. Continue pushing creative choices to build a more distinct editorial voice.'),
  (1, 'editing', 'B', 'Editing: Narrative progression is clear and continuity is maintained well. Focus on moving beyond functional cutting to create stronger emotional expression.'),
  (1, 'editing', 'B', 'Editing: Demonstrates reliable technical execution in Adobe Premiere Pro. Develop more confidence in shaping mood through timing and pauses.'),
  (1, 'editing', 'B', 'Editing: Shot sequencing supports story clarity. Continue improving emotional intention so scenes feel less mechanical and more expressive.'),
  (1, 'editing', 'B', 'Editing: Editing choices communicate the story effectively. Focus on using shot duration more purposefully to strengthen rhythm and engagement.'),
  (1, 'editing', 'B', 'Editing: Shows good understanding of continuity principles. Develop stronger emotional layering and reaction timing within scenes.'),
  (1, 'editing', 'B', 'Editing: Some strong emotional moments are visible. Improve consistency in pacing and continuity across the full sequence.'),
  (1, 'editing', 'B', 'Editing: Demonstrates effort to shape progression beyond basic cuts. Continue refining shot arrangement for stronger narrative emphasis.'),
  (1, 'editing', 'B', 'Editing: Storytelling intent is visible and technically stable. Focus on pacing, emotional beats, and viewer engagement to reach a more advanced level.'),
  (1, 'editing', 'C', 'Editing: Basic continuity and sequencing are visible. Focus on shaping clearer emotional progression through timing, pauses, and reactions.'),
  (1, 'editing', 'C', 'Editing: Demonstrates understanding of shot placement. Improve narrative flow so scenes build stronger meaning and engagement.'),
  (1, 'editing', 'C', 'Editing: Some variation in shot choices is present. Develop more purposeful framing and editing decisions to support storytelling.'),
  (1, 'editing', 'C', 'Editing: Shows effort in scene construction. Focus on controlling pacing more carefully to avoid uneven rhythm.'),
  (1, 'editing', 'C', 'Editing: Basic technical handling is visible. Spend more time practising Adobe Premiere Pro workflows to reduce rough cuts and timing inconsistencies.'),
  (1, 'editing', 'C', 'Editing: Action and continuity are understandable. Develop stronger emotional shaping through pauses, reactions, and shot duration.'),
  (1, 'editing', 'C', 'Editing: Narrative intent is present in parts. Improve scene connections and progression to create smoother continuity.'),
  (1, 'editing', 'C', 'Editing: Engagemnet and participation in exercises is visible. Build consistency across progression, emotional timing, and technical execution to reach the expected standard.'),
  (1, 'editing', 'D', 'Editing: Demonstrates basic effort in assembling scenes. Focus on understanding how shot order creates meaning and progression for clearer storytelling.'),
  (1, 'editing', 'D', 'Editing: Some continuity principles are visible. Improve cut choices and transitions to maintain smoother viewer flow and orientation.'),
  (1, 'editing', 'D', 'Editing: Shows extreme willingness to experiment with pacing. Pause and reflect to develop logical control over shot duration to avoid rushing or stagnanting scenes.'),
  (1, 'editing', 'D', 'Editing: Basic scene structure is present. Focus on selecting shots that better support emotional intent and narrative clarity.'),
  (1, 'editing', 'D', 'Editing: Traces of initial familiarity with editing software is visible. Spend more time practising Adobe Premiere Pro tools and workflows to improve output quality.'),
  (1, 'editing', 'D', 'Editing: Attempts to construct emotional moments are visible. Improve the use of reactions, pauses, and rhythm to build audience engagement.'),
  (1, 'editing', 'D', 'Editing: Regular attendance and active involvement in classroom exercises and productions are necessary to build confidence in editing practice, workflow management, and collaborative learning.'),
  (1, 'editing', 'D', 'Editing: Participation in the editing process is visible. Continue practising progression, pacing, continuity, and technical workflows to reach the expected course level.'),
  (1, 'sound_design', 'A', 'Sound Design: Demonstrates high-level clarity in Human Auditory System. Continue observing the real world soundscapes on a daily basis.'),
  (1, 'sound_design', 'A', 'Sound Design: Demonstrates high-level clarity in Properties and Behaviour of Sound & Aural Perception vs Microphone Behaviour. Observe and analyse self-aural behaviour in everyday life.'),
  (1, 'sound_design', 'A', 'Sound Design: Demonstrates high-level clarity in Audio-Visual Relationships & Spatial and Temporal Relationships of Sound. Research into variations in familiar soundscapes through the days and seasons.'),
  (1, 'sound_design', 'A', 'Sound Design: Demonstrates high-level control and clarity in Portable Audio Recording Devices. Explore all the features available of the devices.'),
  (1, 'sound_design', 'A', 'Sound Design: Demonstrates high-level control and clarity in Location Sound Recording. Keep practising to achieve smoother consistent recordings.'),
  (1, 'sound_design', 'A', 'Sound Design: Demonstrates high-level clarity in Recording & Editing Ambiences. Work towards decoding the individual layers of the ambience recordings.'),
  (1, 'sound_design', 'A', 'Sound Design: Demonstrates high-level clarity in Editing & Mixing Sound Elements using Sound Editing Software. Work towards achieving better mixes for more narrative impact.'),
  (1, 'sound_design', 'A', 'Sound Design: Demonstrates high-level control and clarity in all the Semester I learning outcomes. Practice more with different raw materials across different genres.'),
  (1, 'sound_design', 'B', 'Sound Design: Shows good understanding in Human Auditory System. Focus on understanding the workings of the human ear more.'),
  (1, 'sound_design', 'B', 'Sound Design: Shows good understanding in Properties and Behaviour of Sound & Aural Perception vs Microphone Behaviour. Actively analyse self hearing patterns.'),
  (1, 'sound_design', 'B', 'Sound Design: Shows good understanding in Audio-Visual Relationships & Spatial and Temporal Relationships of Sound. Focus on understanding tonal perspectives of sounds with their corresponding visuals.'),
  (1, 'sound_design', 'B', 'Sound Design: Shows good understanding and execution in Portable Audio Recording Devices. Practice with more recording sessions.'),
  (1, 'sound_design', 'B', 'Sound Design: Shows good understanding and execution in Location Sound Recording. Focus on getting the recording workflow more efficient.'),
  (1, 'sound_design', 'B', 'Sound Design: Shows good understanding and execution in Recording & Editing Ambiences. Aim for getting richer sound textures and cleaner recordings.'),
  (1, 'sound_design', 'B', 'Sound Design: Shows good understanding and execution in Editing & Mixing Sound Elements using Sound Editing Software. Focus on making the post-production workflow more efficient.'),
  (1, 'sound_design', 'B', 'Sound Design: Shows good understanding and execution in all the Semester I learning outcomes. Practise and fine tune all learnings.'),
  (1, 'sound_design', 'C', 'Sound Design: Basic understanding in Human Auditory System. Focus on understanding the workings of the human ear more.'),
  (1, 'sound_design', 'C', 'Sound Design: Basic understanding in Properties and Behaviour of Sound & Aural Perception vs Microphone Behaviour. Requires regular listening to surrounding environments.'),
  (1, 'sound_design', 'C', 'Sound Design: Basic understanding in Audio-Visual Relationships & Spatial and Temporal Relationships of Sound.'),
  (1, 'sound_design', 'C', 'Sound Design: Basic capability in Portable Audio Recording Devices. Refer to the equipment manuals to gain more knowledge.'),
  (1, 'sound_design', 'C', 'Sound Design: Basic capability in Location Sound Recording. Going through the reference materials will help in better understanding.'),
  (1, 'sound_design', 'C', 'Sound Design: Basic capability in Recording & Editing Ambiences. Continue going for more recording trips and upgrade the skills.'),
  (1, 'sound_design', 'C', 'Sound Design: Basic capability in Editing & Mixing Sound Elements using Sound Editing Software. Develop more confidence through practice.'),
  (1, 'sound_design', 'C', 'Sound Design: Basic capability in all the Semester I learning outcomes. Actively practicing outside of class hours will be beneficial.'),
  (1, 'sound_design', 'D', 'Sound Design: Requires significant improvement in Human Auditory System.'),
  (1, 'sound_design', 'D', 'Sound Design: Requires significant improvement in Properties and Behaviour of Sound & Aural Perception vs Microphone Behaviour.'),
  (1, 'sound_design', 'D', 'Sound Design: Requires significant improvement in Audio-Visual Relationships & Spatial and Temporal Relationships of Sound.'),
  (1, 'sound_design', 'D', 'Sound Design: Requires significant improvement in Portable Audio Recording Devices.'),
  (1, 'sound_design', 'D', 'Sound Design: Requires to participate in practical classes to improve in Location Sound Recording.'),
  (1, 'sound_design', 'D', 'Sound Design: Requires to purchase and start using the mandatory recording equipment to start Recording & Editing Ambiences.'),
  (1, 'sound_design', 'D', 'Sound Design: Needs to start with basics of Editing & Mixing Sound Elements using Sound Editing Software.'),
  (1, 'sound_design', 'D', 'Sound Design: Must attend classes regularly to achieve improvement in all the Semester learning outcomes.'),
  (1, 'production', 'A', 'Production: Displays masterful technical command, ensuring that all production elements are polished and professionally executed.'),
  (1, 'production', 'A', 'Production: Demonstrates a sophisticated understanding of the brief, translating complex ideas into clear, semi-aligned outcomes with precision.'),
  (1, 'production', 'A', 'Production: Every production choice is backed by strong intent, showing a purposeful connection between the initial concept and the final result.'),
  (1, 'production', 'A', 'Production: High-level execution is evident throughout the project; the work is finished to a superior standard with meticulous attention to detail.'),
  (1, 'production', 'A', 'Production: Successfully achieves semi-aligned outcomes that bridge the gap between creative experimentation and disciplined production.'),
  (1, 'production', 'A', 'Production: Maintains a high level of control across all phases of the project, ensuring a cohesive and unified final production.'),
  (1, 'production', 'A', 'Production: Exhibits decisive and intelligent control over the medium, opting for solutions that enhance the clarity.'),
  (1, 'production', 'A', 'Production: Demonstrates a powerful sense of resolve; the work is not only well-produced but carries the weight of clear, craftsmanship.'),
  (1, 'production', 'B', 'Production: Demonstrates a solid grasp of technical skills, though needs to work on minor inconsistencies in the final project.'),
  (1, 'production', 'B', 'Production: Shows a clear understanding of the project goals, though the connection between concept and outcome could be more explicit.'),
  (1, 'production', 'B', 'Production: Execution is generally strong, though some areas would benefit from more rigorous quality control and attention to detail.'),
  (1, 'production', 'B', 'Production: Outcomes are semi-aligned with the brief, showing a functional bridge between theory and practical application.'),
  (1, 'production', 'B', 'Production: The work is effective and well-produced, yet there remains visible scope for refinement in the final aesthetic/technical layers.'),
  (1, 'production', 'B', 'Production: Intent is evident throughout the production process, but deeper exploration is needed to move beyond standard solutions.'),
  (1, 'production', 'B', 'Production: Maintains a consistent workflow; however, greater precision in the middle stages would yield a more results.'),
  (1, 'production', 'B', 'Production: The production shows good internal logic and structure, requiring only minor adjustments to achieve high-level clarity.'),
  (1, 'production', 'C', 'Production: Displays a basic capability in core production tasks, though the application of these skills is not yet fully realized.'),
  (1, 'production', 'C', 'Production: While the main components are present, the work lacks the precision required for a polished or professional finish.'),
  (1, 'production', 'C', 'Production: Demonstrates the ability to complete tasks, needs to work on the quality of output across different stages.'),
  (1, 'production', 'C', 'Production: Basic technical requirements have been met, yet inconsistencies in execution detract from the overall impact of the outcome.'),
  (1, 'production', 'C', 'Production: Outcomes show a general understanding of the brief, needs to work on the alignment between intent and result is often loose or vague.'),
  (1, 'production', 'C', 'Production: Shows an awareness of necessary processes, work on minor errors are visible in the final production.'),
  (1, 'production', 'C', 'Production: While the work is functional, your next step is to prioritize precision. Dedicate more time to the attention to detail.'),
  (1, 'production', 'C', 'Production: Demonstrates a developing control over the medium, though further practice is needed to manage tools with steady consistency.'),
  (1, 'production', 'D', 'Production: Struggles to apply core concepts; a stronger focus on the basic fundamentals of the subject is required for progress.'),
  (1, 'production', 'D', 'Production: Execution is currently fragmented, with significant gaps in the production process that hinder a successful outcome.'),
  (1, 'production', 'D', 'Production: Frequent technical errors are present, suggesting a need for intensive practice with the basic tools and techniques.'),
  (1, 'production', 'D', 'Production: Work on sustaining your execution until the project meets all final requirements.'),
  (1, 'production', 'D', 'Production: The final outcome shows limited alignment with the project requirements, necessitating a more focused approach to the brief.'),
  (1, 'production', 'D', 'Production: Aim for a cleaner, more precise execution to reflect the required standard.'),
  (1, 'production', 'D', 'Production: Finds it difficult to translate theoretical instructions into practical production, resulting in underdeveloped outcomes.'),
  (1, 'production', 'D', 'Production: Work produced is sporadic in quality, indicating that a more disciplined and consistent approach to production is essential.'),
  (2, 'direction', 'A', 'Direction: Demonstrates strong control over staging and blocking, using space, movement, and composition with clear narrative intention.'),
  (2, 'direction', 'A', 'Direction: Works effectively with actors, guiding performances with clarity, consistency, and sensitivity to character needs.'),
  (2, 'direction', 'A', 'Direction: Shows a nuanced understanding of scene construction, integrating performance, blocking, and visual elements cohesively.'),
  (2, 'direction', 'A', 'Direction: Applies staging patterns (I, A, L, C, S) effectively to support visual storytelling and spatial dynamics.'),
  (2, 'direction', 'A', 'Direction: Demonstrates strong command over visualisation tools, including storyboards and mood boards, to clearly communicate directorial intent.'),
  (2, 'direction', 'A', 'Direction: Shows clarity in using props and space meaningfully to support narrative and character behaviour.'),
  (2, 'direction', 'A', 'Direction: Demonstrates control over rhythm and pacing, shaping scenes effectively through performance and visual flow.'),
  (2, 'direction', 'A', 'Direction: Shows maturity in handling complex staging situations, including working with VFX-based or virtual elements.'),
  (2, 'direction', 'B', 'Direction: Shows a good understanding of staging and blocking, with scope to improve consistency in execution for more complex scenes.'),
  (2, 'direction', 'B', 'Direction: Works with actors effectively in parts, with scope to strengthen continuity and control of performances across scenes.'),
  (2, 'direction', 'B', 'Direction: Demonstrates an understanding of scene construction, though integration of elements can be further refined for coherence.'),
  (2, 'direction', 'B', 'Direction: Uses staging patterns with some awareness, with scope for more precise and consistent application.'),
  (2, 'direction', 'B', 'Direction: Uses visualisation tools adequately, with scope to add greater clarity and depth in planning.'),
  (2, 'direction', 'B', 'Direction: Shows awareness of rhythm and pacing, with scope to improve consistency in maintaining it across scenes.'),
  (2, 'direction', 'B', 'Direction: Shows awareness of rhythm and pacing, shall improve to maintain it consistently.'),
  (2, 'direction', 'B', 'Direction: Engages with advanced staging concepts, with scope to strengthen consistency in execution.'),
  (2, 'direction', 'C', 'Direction: Shows developing control over staging and blocking, with scope to create clearer and more motivated movement.'),
  (2, 'direction', 'C', 'Direction: Shows developing ability in directing actors, with scope to achieve more consistent and clearer performances.'),
  (2, 'direction', 'C', 'Direction: Scene construction shows developing cohesion, with scope to better integrate visual and performance elements.'),
  (2, 'direction', 'C', 'Direction: Shows developing understanding of staging patterns, with scope to strengthen application.'),
  (2, 'direction', 'C', 'Direction: Visualisation tools can be used more effectively to enhance clarity and planning.'),
  (2, 'direction', 'C', 'Direction: Use of props and space shows developing intent, with scope to make choices more purposeful and motivated by narrative.'),
  (2, 'direction', 'C', 'Direction: Rhythm and pacing show developing control, with scope to improve consistency and overall scene engagement.'),
  (2, 'direction', 'C', 'Direction: Shows developing ability to handle complex staging situations, including those involving VFX or spatial planning.'),
  (2, 'direction', 'D', 'Direction: Shows emerging understanding of staging and blocking, with scope to build more effective scene construction.'),
  (2, 'direction', 'D', 'Direction: Shows emerging ability to direct actors, with scope to achieve clearer and more engaged performances.'),
  (2, 'direction', 'D', 'Direction: Scene construction shows developing coherence, with scope to better integrate visual and performance elements.'),
  (2, 'direction', 'D', 'Direction: Shows emerging understanding of staging patterns and spatial dynamics, with scope for further development.'),
  (2, 'direction', 'D', 'Direction: Visualisation tools need to be used more effectively to support scene planning.'),
  (2, 'direction', 'D', 'Direction: Use of props and space shows emerging intent, with scope to make choices more purposeful within scenes.'),
  (2, 'direction', 'D', 'Direction: Shows emerging control over rhythm and pacing, with scope to improve consistency.'),
  (2, 'direction', 'D', 'Direction: Shows developing engagement with the practical requirements of directing exercises, with scope for stronger application.'),
  (2, 'screenwriting', 'A', 'Screenwriting: Writes dialogue that is natural, character-driven, and effectively reveals subtext with minimal reliance on exposition.'),
  (2, 'screenwriting', 'A', 'Screenwriting: Demonstrates strong control over scene writing, with clear progression, conflict, and purpose in each scene.'),
  (2, 'screenwriting', 'A', 'Screenwriting: Applies advanced story structures (Hero’s Journey / Story Circle) effectively to build engaging and well-shaped narratives.'),
  (2, 'screenwriting', 'A', 'Screenwriting: Shows strong understanding of conflict, creating tension that drives the narrative forward.'),
  (2, 'screenwriting', 'A', 'Screenwriting: Demonstrates distinct character voices, making dialogue identifiable and unique to each character.'),
  (2, 'screenwriting', 'A', 'Screenwriting: Writes with strong awareness of rhythm and pacing, allowing scenes to flow naturally and effectively.'),
  (2, 'screenwriting', 'A', 'Screenwriting: Effectively uses dialogue across different situations, adapting tone and style to suit context and character.'),
  (2, 'screenwriting', 'A', 'Screenwriting: Integrates writing with visual thinking, ensuring scenes are cinematic and performable.'),
  (2, 'screenwriting', 'B', 'Screenwriting: Writes dialogue that serves the narrative, though it can sometimes become predictable or overly explanatory.'),
  (2, 'screenwriting', 'B', 'Screenwriting: Demonstrates an understanding of scene construction, though progression and conflict can be further strengthened.'),
  (2, 'screenwriting', 'B', 'Screenwriting: Applies story structures appropriately, though narratives can be developed further for greater depth and originality.'),
  (2, 'screenwriting', 'B', 'Screenwriting: Shows awareness of conflict, though it can be developed more consistently across the script.'),
  (2, 'screenwriting', 'B', 'Screenwriting: Characters show some distinction, though dialogue voices can be further differentiated.'),
  (2, 'screenwriting', 'B', 'Screenwriting: Demonstrates basic control over pacing, though scenes can feel uneven at times.'),
  (2, 'screenwriting', 'B', 'Screenwriting: Writes dialogue suited to situations, though there is scope for greater tonal variation.'),
  (2, 'screenwriting', 'B', 'Screenwriting: Shows an understanding of cinematic writing, though execution can be strengthened for greater impact.'),
  (2, 'screenwriting', 'C', 'Screenwriting: Dialogue shows developing depth, though it can sometimes become functional or overly explanatory. Focus on subtext and character-specific speech patterns so conversations feel more natural and emotionally layered.'),
  (2, 'screenwriting', 'C', 'Screenwriting: Scene writing shows developing consistency, though progression and purpose can be made clearer.'),
  (2, 'screenwriting', 'C', 'Screenwriting: Shows developing understanding of story structures, with scope to strengthen narrative flow.'),
  (2, 'screenwriting', 'C', 'Screenwriting: Conflict shows emerging development, though clarity and consistency can be further strengthened.'),
  (2, 'screenwriting', 'C', 'Screenwriting: Characters show developing voices, though dialogue can sometimes feel repetitive and needs more distinction.'),
  (2, 'screenwriting', 'C', 'Screenwriting: Pacing shows developing control, though rhythm can feel uneven at times. Practice restructuring scenes and tightening transitions so the narrative flow feels smoother and more engaging.'),
  (2, 'screenwriting', 'C', 'Screenwriting: Dialogue shows developing alignment with situation and character intent, with scope for greater clarity.'),
  (2, 'screenwriting', 'C', 'Screenwriting: Writing shows emerging cinematic quality, though scenes need clearer visualization and stronger performative potential.'),
  (2, 'screenwriting', 'D', 'Screenwriting: Dialogue shows emerging clarity, though it needs further development in purpose and character distinction.'),
  (2, 'screenwriting', 'D', 'Screenwriting: Scene writing shows emerging structure, with scope to develop clearer beginnings, progression, and resolution.'),
  (2, 'screenwriting', 'D', 'Screenwriting: Shows emerging understanding of story structures, with scope to strengthen narrative progression.'),
  (2, 'screenwriting', 'D', 'Screenwriting: Conflict shows emerging development, though it needs clearer articulation and consistency.'),
  (2, 'screenwriting', 'D', 'Screenwriting: Characters show early-stage development, with scope to build clearer voice and motivation.'),
  (2, 'screenwriting', 'D', 'Screenwriting: Pacing shows emerging control, though writing may feel disjointed at times. Practice restructuring scenes and tightening transitions so the narrative flow feels smoother and more engaging.'),
  (2, 'screenwriting', 'D', 'Screenwriting: Dialogue shows developing alignment with situation and character, with scope to improve credibility and clarity.'),
  (2, 'screenwriting', 'D', 'Screenwriting: Shows developing engagement with basic screenwriting skills required for the course, with scope for further improvement.'),
  (2, 'cinematography', 'A', 'Demonstrates clear understanding of motivated camera movement, with each movement supporting narrative intent.'),
  (2, 'cinematography', 'A', 'Controls rhythm, pace and tempo effectively, enhancing the visual flow of the scene.'),
  (2, 'cinematography', 'A', 'Constructs well-planned camera movements that contribute meaningfully to storytelling.'),
  (2, 'cinematography', 'A', 'Integrates emotion with camera movement, strengthening the impact of the scene.'),
  (2, 'cinematography', 'A', 'Executes basic camera movements such as pan and tilt with precision and smooth control.'),
  (2, 'cinematography', 'A', 'Adapts confidently to available light, making informed visual decisions on set.'),
  (2, 'cinematography', 'A', 'Applies foundational lighting techniques effectively, including three-point lighting and bounce control.'),
  (2, 'cinematography', 'A', 'Develops and executes clear lighting plans that align with the visual requirements of the scene.'),
  (2, 'cinematography', 'B', 'Demonstrates a good understanding of camera movement, with scope to strengthen the motivation behind each movement.'),
  (2, 'cinematography', 'B', 'Maintains a sense of rhythm and pacing, greater consistency can enhance the overall visual flow.'),
  (2, 'cinematography', 'B', 'Plans camera movements with intent and can refine their alignment with narrative progression.'),
  (2, 'cinematography', 'B', 'Connects emotion with camera movement in parts and can strengthen this relationship to enhance storytelling impact.'),
  (2, 'cinematography', 'B', 'Executes basic camera movements such as pan and tilt with control and can improve smoothness and precision.'),
  (2, 'cinematography', 'B', 'Responds to available light with awareness and can refine decision-making to achieve more consistent visual results.'),
  (2, 'cinematography', 'B', 'Applies foundational lighting techniques and can strengthen control over shaping and balancing light.'),
  (2, 'cinematography', 'B', 'Establishes basic lighting plans, with further refinement improving clarity and effectiveness for the scene.'),
  (2, 'cinematography', 'C', 'Shows a basic understanding of camera movement and can improve by focusing on the purpose behind each movement.'),
  (2, 'cinematography', 'C', 'Demonstrates an emerging sense of rhythm and pacing and can strengthen visual flow through more consistent execution.'),
  (2, 'cinematography', 'C', 'Attempts to plan camera movements and can improve by aligning them more clearly with the scene’s progression.'),
  (2, 'cinematography', 'C', 'Shows initial connection between emotion and movement and can develop this further to support storytelling.'),
  (2, 'cinematography', 'C', 'Executes basic camera movements such as pan and tilt at a functional level and can improve control through regular practice.'),
  (2, 'cinematography', 'C', 'Shows awareness of available light and can strengthen results by making more consistent visual decisions.'),
  (2, 'cinematography', 'C', 'Applies basic lighting techniques and can improve by developing better control over light direction and balance.'),
  (2, 'cinematography', 'C', 'Demonstrates a developing approach to lighting plans and can strengthen clarity by planning setups more deliberately.'),
  (2, 'cinematography', 'D', 'Is at an early stage in understanding camera movement and should focus on learning the purpose behind each movement.'),
  (2, 'cinematography', 'D', 'Shows limited control over rhythm and pacing and can improve by practicing steady and consistent shot execution.'),
  (2, 'cinematography', 'D', 'Camera movements require further planning and can develop through focusing on simple and clear shot progression.'),
  (2, 'cinematography', 'D', 'Connection between emotion and movement is still developing and can improve by understanding how movement supports storytelling.'),
  (2, 'cinematography', 'D', 'Basic camera movements such as pan and tilt require greater control and can be strengthened through guided practice.'),
  (2, 'cinematography', 'D', 'Understanding of available light is at an early stage and can improve by observing and adapting to light conditions more carefully.'),
  (2, 'cinematography', 'D', 'Lighting application requires development and can be strengthened by focusing on fundamental techniques such as key, fill and backlight.'),
  (2, 'cinematography', 'D', 'Lighting plans need clearer structure and can improve by practicing simple setups before moving to complex scenes.'),
  (2, 'editing', 'A', 'Editing: Demonstrates strong control over dialogue, continuity, pacing, montage, and VFX integration. Continue refining conceptual layering and emotional nuance for greater depth.'),
  (2, 'editing', 'A', 'Editing: Dialogue rhythm and pacing are handled confidently. Explore more complex montage relationships and thematic connections to strengthen meaning.'),
  (2, 'editing', 'A', 'Editing: Shows strong montage thinking and visual linking. Continue refining continuity precision and emotional timing for smoother flow.'),
  (2, 'editing', 'A', 'Editing: Emotional shaping through reactions and pacing is highly effective. Improve technical consistency in VFX integration for a more polished output.'),
  (2, 'editing', 'A', 'Editing: Demonstrates clean continuity and strong visual storytelling. Continue developing pauses, silence, and emotional layering for richer scene construction.'),
  (2, 'editing', 'A', 'Editing: Sound-image interplay and pacing are handled with maturity. Explore more conceptual experimentation within montage structures.'),
  (2, 'editing', 'A', 'Editing: Shot relationships and visual composition support storytelling effectively. Refine dialogue pacing and sound layering for greater tonal control.'),
  (2, 'editing', 'A', 'Editing: Confident and creative editorial choices are evident throughout. Continue balancing experimentation with continuity precision and narrative clarity.'),
  (2, 'editing', 'B', 'Editing: Dialogue scenes are engaging and structurally clear. Focus on developing stronger conceptual montage connections and smoother VFX integration.'),
  (2, 'editing', 'B', 'Editing: Demonstrates good visual linking and pacing awareness. Improve continuity precision and emotional shaping within dialogue scenes.'),
  (2, 'editing', 'B', 'Editing: Technical execution is stable and VFX handling is functional. Develop stronger emotional depth through timing, pauses, and reactions.'),
  (2, 'editing', 'B', 'Editing: Emotional rhythm and reaction timing are effective in parts. Continue refining technical consistency and VFX integration.'),
  (2, 'editing', 'B', 'Editing: Shows understanding across dialogue, montage, rhythm and VFX. Focus on integrating these areas more cohesively across the sequence.'),
  (2, 'editing', 'B', 'Editing: Spatial and temporal continuity are maintained well. Push creative experimentation further to avoid overly safe editing choices.'),
  (2, 'editing', 'B', 'Editing: Pacing works effectively in sections. Improve continuity and narrative clarity across transitions and scene progression.'),
  (2, 'editing', 'B', 'Editing: Shot choices support story progression clearly. Continue developing sound layering and silence as narrative tools.'),
  (2, 'editing', 'C', 'Editing: Story structure is partially understandable. Focus on creating clearer montage relationships and integrating VFX more meaningfully.'),
  (2, 'editing', 'C', 'Editing: Attempts at conceptual linking are visible. Improve continuity and dialogue shaping to strengthen viewer clarity.'),
  (2, 'editing', 'C', 'Editing: Some emotionally effective moments are present. Work on maintaining more consistent pacing and rhythm throughout scenes.'),
  (2, 'editing', 'C', 'Editing: Basic continuity awareness is visible. Improve eyelines, screen direction, and movement matching for smoother viewing.'),
  (2, 'editing', 'C', 'Editing: Dialogue and scene structure are partially functional. Develop stronger use of pauses, reactions, and silence for emotional engagement.'),
  (2, 'editing', 'C', 'Editing: Technical effort is visible. Spend more time refining cuts, timing, and VFX execution to improve overall quality.'),
  (2, 'editing', 'C', 'Editing: Some variation in composition and shot choice is present. Focus on guiding viewer attention more purposefully through editing decisions.'),
  (2, 'editing', 'C', 'Editing: Student joyfully participates in montage and dialogue exercises. Building technical efficiecy across rhythm, continuity, sound, and storytelling will make that participation effective.'),
  (2, 'editing', 'D', 'Editing: Demonstrates effort in constructing dialogue scenes. Focus on improving continuity and structure so scenes become easier to follow.'),
  (2, 'editing', 'D', 'Editing: Some awareness of spatial continuity is visible. Develop stronger control over eyelines, movement direction, and screen logic.'),
  (2, 'editing', 'D', 'Editing: Attempts at pacing and rhythm are present. Improve timing control to avoid scenes feeling rushed or prolonged.'),
  (2, 'editing', 'D', 'Editing: Basic sound placement is present. Focus on integrating dialogue, silence, and sound more meaningfully with visuals.'),
  (2, 'editing', 'D', 'Editing: Shows initial experimentation with montage. Develop stronger thematic and conceptual connections between shots.'),
  (2, 'editing', 'D', 'Editing: Interest in graphics and effects is visible. Spend more time refining technical execution so effects support storytelling effectively.'),
  (2, 'editing', 'D', 'Editing: Some shot variation is attempted. Improve shot selection and sequencing to strengthen clarity and audience engagement.'),
  (2, 'editing', 'D', 'Editing: Regular attendance and active involvement in classroom exercises and productions are necessary to build confidence in editing practice, workflow management, and collaborative learning.'),
  (2, 'sound_design', 'A', 'Sound Design: Demonstrates high-level clarity in Attributes of Tonality, Pitch, and Amplitude in Dialogue Scenes. Start comparing between different characters, situations, & inter-persoanl relations through watching films and shows.'),
  (2, 'sound_design', 'A', 'Sound Design: Demonstrates high-level clarity in Characteristics and Applications of Different Microphones. Explore more by using them  in different scenarios.'),
  (2, 'sound_design', 'A', 'Sound Design: Demonstrates high-level control and clarity in Different Audio Devices used in Sound Production. Experiment with different brands and models to understand differences in features and quality.'),
  (2, 'sound_design', 'A', 'Sound Design: Demonstrates high-level control and clarity in Sound Recording & Sound Editing of Dialogue Scenes. Research into advanced techniques utilized on professional film productions.'),
  (2, 'sound_design', 'A', 'Sound Design: Demonstrates high-level clarity in Workflow from Pre-Production to Post-Production of Sound in Film & TV Industry.'),
  (2, 'sound_design', 'A', 'Sound Design: Demonstrates high-level control and clarity in Making Sound Stories. Can experiment with different genres and research into the business side of the industry.'),
  (2, 'sound_design', 'A', 'Sound Design: Demonstrates high-level control and clarity in Sound Designing for Animation & VFX. Should work on practice projects and start building a demo showreel.'),
  (2, 'sound_design', 'A', 'Sound Design: Demonstrates high-level control and clarity in all the Semester II learning outcomes.'),
  (2, 'sound_design', 'B', 'Sound Design: Shows good understanding in Attributes of Tonality, Pitch, and Amplitude in Dialogue Scenes. Implement the learnings into different scenarios to understand the nuances.'),
  (2, 'sound_design', 'B', 'Sound Design: Shows good understanding in Characteristics and Applications of Different Microphones. Research into what makes them different from each other.'),
  (2, 'sound_design', 'B', 'Sound Design: Shows good understanding and execution in Different Audio Devices used in Sound Production. Read the equipment manuals and explore all the features available in each device.'),
  (2, 'sound_design', 'B', 'Sound Design: Shows good understanding and execution in Sound Recording & Sound Editing of Dialogue Scenes. Can fine tune skills and research into workflows of professional films.'),
  (2, 'sound_design', 'B', 'Sound Design: Shows good understanding in Workflow from Pre-Production to Post-Production of Sound in Film & TV Industry.'),
  (2, 'sound_design', 'B', 'Sound Design: Shows good understanding and execution in Making Sound Stories. Experiment with different genres.'),
  (2, 'sound_design', 'B', 'Sound Design: Shows good understanding and execution in Sound Designing for Animation & VFX. Experiment with different effects and sound layers and edits.'),
  (2, 'sound_design', 'B', 'Sound Design: Shows good understanding and execution in all the Semester II learning outcomes. Encouraged to refine and fine tune skills by more practice projects.'),
  (2, 'sound_design', 'C', 'Sound Design: Basic capability in Attributes of Tonality, Pitch, and Amplitude in Dialogue Scenes. Requires to watch more films and shows and observe all the sound attributes.'),
  (2, 'sound_design', 'C', 'Sound Design: Basic capability in Characteristics and Applications of Different Microphones. Must do test recordings and compare the quality of different microphones.'),
  (2, 'sound_design', 'C', 'Sound Design: Basic capability in Different Audio Devices used in Sound Production. Must read about different audio devices to better understand the purpose of each equipment.'),
  (2, 'sound_design', 'C', 'Sound Design: Basic capability in Sound Recording & Sound Editing of Dialogue Scenes. Skills can be improved with more practice and analysing the recordings.'),
  (2, 'sound_design', 'C', 'Sound Design: Basic capability in Workflow from Pre-Production to Post-Production of Sound in Film & TV Industry.'),
  (2, 'sound_design', 'C', 'Sound Design: Basic capability in Making Sound Stories. Work on building the story world with respect to the soundscape.'),
  (2, 'sound_design', 'C', 'Sound Design: Basic capability in Sound Designing for Animation & VFX. Should watch behind the scenes interviews and videos of animation films.'),
  (2, 'sound_design', 'C', 'Sound Design: Basic capability in all the Semester II learning outcomes. Requires more pro-activeness to imrove knowledge and skills.'),
  (2, 'sound_design', 'D', 'Sound Design: Requires significant improvement in Attributes of Tonality, Pitch, and Amplitude in Dialogue Scenes. Requires to listen and concentrate on soundscapes of films.'),
  (2, 'sound_design', 'D', 'Sound Design: Requires significant improvement in Characteristics and Applications of Different Microphones. Requires active observation about sound in films, shows, live events, concerts, sports etc.'),
  (2, 'sound_design', 'D', 'Sound Design: Requires significant improvement in Different Audio Devices used in Sound Production.'),
  (2, 'sound_design', 'D', 'Sound Design: Requires significant improvement in Sound Recording & Sound Editing of Dialogue Scenes. Requires to participate in practical exercises.'),
  (2, 'sound_design', 'D', 'Sound Design: Requires significant improvement in Workflow from Pre-Production to Post-Production of Sound in Film & TV Industry.'),
  (2, 'sound_design', 'D', 'Sound Design: Requires significant improvement in Making Sound Stories. Must explore the world of audiobooks and audio stories.'),
  (2, 'sound_design', 'D', 'Sound Design: Requires significant improvement in Sound Designing for Animation & VFX. Must work on more sample projects.'),
  (2, 'sound_design', 'D', 'Sound Design: Requires significant improvement in all the Semester II learning outcomes. Must attend classes regularly to understand the basics.'),
  (2, 'production', 'A', 'Production: Demonstrates a sophisticated ability to synthesize complex ideas into cohesive, high-level outcomes with seamless control.'),
  (2, 'production', 'A', 'Production: Shows exceptional clarity in aligning Semester objectives with final outputs, ensuring every element serves the intended purpose.'),
  (2, 'production', 'A', 'Production: Execution is of a professional standard, characterized by meticulous attention to detail and a refined technical finish.'),
  (2, 'production', 'A', 'Production: Every production decision is driven by strong, discernible intent, reflecting a deep conceptual understanding of the medium.'),
  (2, 'production', 'A', 'Production: Displays a high degree of technical fluency, navigating Semester challenges with confidence and creative autonomy.'),
  (2, 'production', 'A', 'Production: Goes beyond the basic requirements to optimize outcomes, showing a proactive approach to elevating the quality of the work.'),
  (2, 'production', 'A', 'Production: Maintains rigorous control over the production workflow, resulting in outcomes that are both polished and conceptually sound.'),
  (2, 'production', 'A', 'Production: The work exhibits a rare level of clarity; the student’s vision is translated perfectly through strong execution and discipline.'),
  (2, 'production', 'B', 'Production: Demonstrates a solid grasp of Semester II concepts, successfully applying them to create functional and effective outcomes.'),
  (2, 'production', 'B', 'Production: Execution is strong and reliable, though further refinement is needed to achieve a truly professional-grade finish.'),
  (2, 'production', 'B', 'Production: Shows good alignment between project objectives and the final product, with minor gaps where intent could be clearer.'),
  (2, 'production', 'B', 'Production: The work is well-developed, yet there remains visible scope for refinement in the more intricate details of the production.'),
  (2, 'production', 'B', 'Production: Maintains good control over the production process throughout the semester, though consistency occasionally wavers under complex tasks.'),
  (2, 'production', 'B', 'Production: Successfully translates Semester theory into practice, producing work that is competent and hits all major benchmarks.'),
  (2, 'production', 'B', 'Production: The work exhibits clear logic and structure; however, further polishing would elevate the overall sophistication of the outcome.'),
  (2, 'production', 'B', 'Production: Shows a clear ability to execute ideas effectively; focus more on your workflow.'),
  (2, 'production', 'C', 'Production: Demonstrates a basic capability in Semester tasks, though the transition to more complex production techniques is still ongoing.'),
  (2, 'production', 'C', 'Production: While the core tasks are met, greater attention to detail is needed to improve the accuracy of your work.'),
  (2, 'production', 'C', 'Production: Production output is variable; maintaining a steady level of quality across all Semester modules remains a key area for growth.'),
  (2, 'production', 'C', 'Production: There is a general alignment with the project brief, but the execution often lacks the clarity to fully communicate the intended outcome.'),
  (2, 'production', 'C', 'Production: Focus on managing multiple technical variables more effectively to avoid inconsistencies in your execution.'),
  (2, 'production', 'C', 'Production: Shows a foundational grasp of Semester  theory, yet struggles to apply these concepts with consistent accuracy in practice.'),
  (2, 'production', 'C', 'Production: While the student is capable of completing the work, a more disciplined approach is needed to eliminate recurring technical errors.'),
  (2, 'production', 'C', 'Production: Work on sustaining your effort from the initial concept through to a more refined and completed state.'),
  (2, 'production', 'D', 'Production: Work on stabilizing your production process to ensure your final outputs are consistent and reliable.'),
  (2, 'production', 'D', 'Production: The execution of practical work is currently underdeveloped, requiring a more rigorous approach to meet basic production standards.'),
  (2, 'production', 'D', 'Production: Needs more practice time to gain the production control.'),
  (2, 'production', 'D', 'Production: Demonstrates limited clarity in how to translate instructions into a finished product; further guidance on core concepts is essential.'),
  (2, 'production', 'D', 'Production: Work on establishing a more efficient workflow to better production handling.'),
  (2, 'production', 'D', 'Production: Focus on a more structured approach to production.'),
  (2, 'production', 'D', 'Production: Outcomes show a significant disconnect from the Semester objectives, indicating a need for better planning and follow-through.'),
  (2, 'production', 'D', 'Production: Aim for a more thorough interpretation of project goals to ensure your execution aligns with the criteria.')
) AS v(semester, subject_code, grade, body)
JOIN public.subjects s ON s.code = v.subject_code
WHERE NOT EXISTS (
  SELECT 1 FROM public.comment_bank cb
  WHERE cb.semester = v.semester AND cb.subject_id = s.id AND cb.body = v.body
);
