// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vnyoexxeqdjpzekjteft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZueW9leHhlcWRqcHpla2p0ZWZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MzQxMTUsImV4cCI6MjA2NDUxMDExNX0.Ta1LilxCNkG_9SX3NEweCU-VrO7xTTXrKMJvsmarghA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);